Add reset offset method to consumer group
remerge/sarama pull request #1
Opened 2017-12-11 15:47 UTC by cedrics

[Trello](https://trello.com/c/sBRYdZvw/2109-use-the-groupconsumer-in-bm-and-in-audi-instead-of-old-consumer-wrappers)

2017-12-20 08:32 UTC, itszootime approved these changes
:+1:

2018-01-23 10:25 UTC, itszootime requested changes
Now `MarkOffset` has changed, please update `MarkMessage` to call `MarkOffset` with `offset+1`

2018-01-23 10:33 UTC, cedrics commented
Omg, I am so stupid 😸  I used to github to search for `MarkMessage` and it didn't find anything - at least I thought so, but you actually can't search the repo because it is a fork. Sorry for that.

2018-01-23 15:35 UTC, itszootime approved these changes

2018-02-06 11:11 UTC, merged